# Generated by Django 5.1.3 on 2024-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_video_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
